# 数据库配置文件
database:
  driver: postgresql
  host: 47.92.216.173
  port: 7654
  database: xian
  username: postgres
  password: zhangsan
  echo: false  # 是否打印SQL语句

# 连接池配置
pool:
  size: 10            # 连接池默认保持的连接数
  max_overflow: 20    # 超过连接池大小时允许的最大连接数
  recycle: 3600       # 连接的最大生存时间(秒)，防止连接失效
  pre_ping: true      # 获取连接前测试连接是否有效
  timeout: 30         # 获取连接的超时时间(秒)
